version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/shoutrrr

workflows:
  version: 2
  shoutrrr:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
jobs:
  checkout:
    executor: go
    steps:
      - checkout
      - persist_to_workspace:
          paths:
            - .
          root: ~/shoutrrr
  build:
    executor: go
    steps:
      - attach_workspace:
            at: .
      - run: go build ./...
      - persist_to_workspace:
          paths:
            - .
          root: ~/shoutrrr
  test:
    executor: go
    steps:
      - attach_workspace:
            at: .
      - run: go get github.com/schrej/godacov
      - run: go get -u github.com/haya14busa/goverage
      - run: goverage -v -coverprofile=coverage.out ./...
      - run: godacov -t $CODACY_TOKEN -r ./coverage.out -c $CIRCLE_SHA1
