version: 1
props:
  Badge:
    type: number
    description: The number displayed next to App icon
    default: "0"
    base: 10
    keys: [badge]
  Category:
    type: text
    description: Reserved field, no use yet
    keys: [category]
  Copy:
    type: text
    description: The value to be copied
    keys: [copy]
  DeviceKey:
    type: text
    description: The key for each device
    required: true
    urlparts: [password]
  Group:
    type: text
    description: The group of the notification
    keys: [group]
  Host:
    type: text
    description: Server hostname and port
    required: true
    urlparts: [host]
  Icon:
    type: text
    description: An url to the icon, available only on iOS 15 or later
    keys: [icon]
  Path:
    type: text
    description: Server path
    default: /
    urlparts: [path1]
  Scheme:
    type: text
    description: Server protocol, http or https
    default: https
    keys: [scheme]
  Sound:
    type: text
    description: Value from https://github.com/Finb/Bark/tree/master/Sounds
    keys: [sound]
  Title:
    type: text
    description: Notification title, optionally set by the sender
    keys: [title]
  URL:
    type: text
    description: Url that will jump when click notification
    keys: [url]
