name: Main Workflow
on: [push]
jobs:
  build:
    name: Build Shoutrrr
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: go build -v .
        
      - name: Install godacov
        run: go get github.com/schrej/godacov

      - name: Test
        run: go test -v -coverprofile=coverage.out ./...
        
      - name: Publish test coverage on Codacy
        run: godacov -t $CODACY_TOKEN -r ./coverage.out -c $CIRCLE_SHA1
